### ISSUE TITLE
What to do when user has no image

### ISSUE THREAD

**Issue by ramsgoli** [ucladevx/governor-acm#17]
<img width="299" alt="screen shot 2017-05-29 at 9 14 52 pm" src="https://cloud.githubusercontent.com/assets/12592200/26567917/1ce55f58-44b4-11e7-9319-02131f30b1e3.png">

When the database doesn't contain a link to a photo, the user icon component freaks out a little. Should we supply a default image url if one isn't present?

**Comment by jl98** [comment]
Use this:

![default](https://cloud.githubusercontent.com/assets/15708594/26568560/41cce4ee-44b9-11e7-994c-1d65f75712ee.png)

**Comment by ramsgoli** [comment]
👍
