### ISSUE TITLE
Suggestion: Change back arrow to Sign Out

### ISSUE THREAD

**Issue by binerys** [ucladevx/governor-acm#26]
## Expected Behavior
Change it to something indicating a sign out since that's what it does

## Current Behavior
I keep on pressing the button instinctively button that i'll be going back to another page. 

## Possible Solution
A good sign out icon to use:
http://fontawesome.io/icon/sign-out/

**Comment by nkansal96** [comment]
@jl98

**Comment by nkansal96** [comment]
Fixed by #27
